spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: config-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
